import type { Meta, StoryObj } from '@storybook/html-vite';
import fixtures from '../fixtures.json';

/**
 * Every story here renders markup GENERATED BY THE REAL PHP RENDERERS
 * (BHY_UI::badge/alert/card/table_wrap), via tools/gen-storybook-fixtures.php.
 *
 * Nothing in this file hand-writes component markup. That is deliberate: a
 * hand-written story is one more copy free to drift from production, which
 * is exactly how this codebase ended up with eight different badge shapes.
 * Regenerate with `npm run storybook:fixtures` after changing a renderer.
 */

type State = { name: string; html: string };
type Fixtures = { generatedAt: string; stories: Record<string, State[]> };
const data = fixtures as Fixtures;

function renderStates(states: State[], stacked = false): HTMLElement {
  const wrap = document.createElement('div');
  wrap.style.display = 'flex';
  wrap.style.flexDirection = stacked ? 'column' : 'row';
  wrap.style.flexWrap = 'wrap';
  wrap.style.gap = '16px';
  wrap.style.alignItems = stacked ? 'stretch' : 'flex-start';

  for (const s of states) {
    const cell = document.createElement('div');
    cell.style.display = 'flex';
    cell.style.flexDirection = 'column';
    cell.style.gap = '6px';
    cell.style.minWidth = stacked ? '100%' : '0';
    cell.style.maxWidth = '100%';

    const label = document.createElement('div');
    label.textContent = s.name;
    label.style.font = '11px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace';
    label.style.opacity = '0.6';
    label.style.letterSpacing = '.03em';
    label.style.textTransform = 'uppercase';

    const host = document.createElement('div');
    host.innerHTML = s.html;

    cell.append(label, host);
    wrap.append(cell);
  }
  return wrap;
}

const meta: Meta = {
  title: 'Design system/Components',
  parameters: {
    docs: {
      description: {
        component:
          'Rendered from the real `BHY_UI::` PHP renderers via ' +
          '`npm run storybook:fixtures` — not hand-written, so it cannot drift ' +
          'from what wp-admin actually ships.',
      },
    },
  },
};
export default meta;

export const Badge: StoryObj = {
  render: () => renderStates(data.stories['Badge']),
  parameters: { docs: { description: { story: 'Status pills. Use for real state, never decoration.' } } },
};

export const Alert: StoryObj = {
  render: () => renderStates(data.stories['Alert'], true),
};

export const Card: StoryObj = {
  render: () => renderStates(data.stories['Card'], true),
};

export const EmptyState: StoryObj = {
  name: 'Empty state',
  render: () => renderStates(data.stories['Empty state'], true),
};

export const WideTable: StoryObj = {
  name: 'Wide table',
  render: () => renderStates(data.stories['Wide table'], true),
  parameters: { layout: 'fullscreen' },
};

/** Everything at once — the fastest way to spot an inconsistency. */
export const Overview: StoryObj = {
  render: () => {
    const root = document.createElement('div');
    root.style.display = 'flex';
    root.style.flexDirection = 'column';
    root.style.gap = '32px';
    for (const [group, states] of Object.entries(data.stories)) {
      const section = document.createElement('section');
      const h = document.createElement('h2');
      h.textContent = group;
      h.style.margin = '0 0 12px';
      section.append(h, renderStates(states, group !== 'Badge'));
      root.append(section);
    }
    return root;
  },
};
